
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  1 2025 14:10:29 IST (Nov  1 2025 08:40:29 UTC)

// Verification Directory fv/top_manchester 

module manchester_decoder(clk, rst, manchester_in, data_out);
  input clk, rst, manchester_in;
  output data_out;
  wire clk, rst, manchester_in;
  wire data_out;
  wire n_0, n_1;
  DFFRHQX1 data_out_reg(.RN (n_0), .CK (clk), .D (n_1), .Q (data_out));
  INVXL g6(.A (manchester_in), .Y (n_1));
  INVXL g7(.A (rst), .Y (n_0));
endmodule

module manchester_encoder(clk, rst, data_in, manchester_out);
  input clk, rst, data_in;
  output manchester_out;
  wire clk, rst, data_in;
  wire manchester_out;
  wire n_0, n_1;
  DFFRHQX1 manchester_out_reg(.RN (n_0), .CK (clk), .D (n_1), .Q
       (manchester_out));
  INVXL g6(.A (data_in), .Y (n_1));
  INVXL g7(.A (rst), .Y (n_0));
endmodule

module top_manchester(clk, rst, data_in, manchester_sig, decoded_out);
  input clk, rst, data_in;
  output manchester_sig, decoded_out;
  wire clk, rst, data_in;
  wire manchester_sig, decoded_out;
  manchester_decoder decoder_inst(.clk (clk), .rst (rst),
       .manchester_in (manchester_sig), .data_out (decoded_out));
  manchester_encoder encoder_inst(.clk (clk), .rst (rst), .data_in
       (data_in), .manchester_out (manchester_sig));
endmodule

